In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data 
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [6]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix
iris = datasets.load_iris()
X = iris.data 
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
cm=confusion_matrix(y_test,y_pred)
print("comfutionmatrix:",cm)

Accuracy: 100.00%
comfutionmatrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [12]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix
data = datasets.load_iris()
X = data.data 
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
cm=confusion_matrix(y_test,y_pred)
print("comfutionmatrix:",cm)
new_flower = [[5.1, 3.5, 1.4, 0.2]]
prediction = nb_classifier.predict(new_flower)
print("Predicted flower:", data.target_names[prediction[0]])

Accuracy: 100.00%
comfutionmatrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Predicted flower: setosa


In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix
df=pd.read_csv("Iris.csv")
X = df.iloc[:, 1:-1].to_numpy(dtype=float)
y = df.iloc[:, -1].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
cm=confusion_matrix(y_test,y_pred)
print("comfutionmatrix:",cm)
j=float(input("enter a first length:"))
o=float(input("enter a first width:"))
b=float(input("enter a first length:"))
i=float(input("enter a first width:"))
new_flo=np.array([[j,o,b,i]])
prediction = nb_classifier.predict(new_flo)
print("Predicted flower:",prediction[0])

Accuracy: 100.00%
comfutionmatrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


enter a first length: 3
enter a first width: 4
enter a first length: 5
enter a first width: 2


Predicted flower: Iris-virginica
